### ISSUE TITLE
Question about Dockerfile

### ISSUE THREAD

**Issue by danielballan** [lnls-sirius/docker-olog-server#1]
Good morning. I have tried to build this Dockerfile, and it errors out on [this step](https://github.com/lnls-sirius/docker-olog-server/blob/master/Dockerfile#L47) like so:

```
Step 23/25 : COPY olog-service-2.2.9.war ${GLASSFISH_CONF_FOLDER}/olog-service-2.2.9.war
COPY failed: stat /var/lib/docker/tmp/docker-builder820107073/olog-service-2.2.9.war: no such file or directory
```

I can't see where `olog-service-2.2.9.war` is supposed to be obtained. I would be grateful for any guidance.

[Edit: It seems like it was maybe removed in [this commit](https://github.com/lnls-sirius/docker-olog-server/commit/8e317e30be01febb85a7a847ab0147e3771070ac)?]

**Comment by gciotto** [comment]
Hello @danielballan,
As this file is heavy (57.1MB), I had chosen not push it into this repository. To make it simpler for you, I'm adding it now into directory `bin`. 
Other alternatives are to obtain the [image](https://hub.docker.com/r/lnlscon/olog-server/) directly from Dockerhub or to compile the source code from [here](https://github.com/Olog/olog-service).

**Comment by danielballan** [comment]
I see. I think your choice not to include a 57.1 MB file in the source is the right one -- no need to re-add it.

**Comment by danielballan** [comment]
~Perhaps I can add a line to the shell script that builds that Docker which will download that file. What is the URL?~

[Edit: See next comment.]

**Comment by danielballan** [comment]
Forgive the "newbie" question -- I'm a Python guy, not a Java guy -- how does one build https://github.com/Olog/olog-service? There is no README, and naively running `./make-distribution` fails because it expects a subdirectory named `target/`, which does not exist in the source tree.

**Comment by gciotto** [comment]
I think that I forgot to mention that you'll need to clone this [project](https://github.com/Olog/olog) with `--recursive` flag. This will also download the repository that I commented in my previous comment.
After that, you use the command `mvn clean install` in `modules/olog-service`. This process is a little tricky, that's why I chose to use an already built binary instead of compiling it in the Dockerfile.

**Comment by danielballan** [comment]
Great, thanks. For now I have downloaded the binary itself -- one problem at a time! :-D

I believe that it is necessary to set the `CERTIFICATE_PASSWORD` env var, like so:

```patch
diff --git a/run-docker-olog.sh b/run-docker-olog.sh
index 00ad02f..e48d45a 100755
--- a/run-docker-olog.sh
+++ b/run-docker-olog.sh
@@ -25,6 +25,6 @@ if [ ! -z ${CONTAINERS:+x} ]; then
     docker rm ${DOCKER_RUN_NAME}
 fi

-docker run -d --name=${DOCKER_RUN_NAME} -e ADMIN_PASSWORD=controle -p 4848:4848 ${DOCKER_MANTAINER_NAME}/${DOCKER_NAME}:${DOCKER_TAG}
+docker run -d --name=${DOCKER_RUN_NAME} -e ADMIN_PASSWORD=controle -e CERTIFICATE_PASSWORD=SOME_PASSWORD -p 4848:4848 ${DOCKER_MANTAINER_NAME}/${DOCKER_NAME}:${DOCKER_TAG}
```

If that seems right to you, I'll submit a PR. Next, having done that, server startup gets pretty far along but ultimately trips on an SSL-related error. I have pasted the [docker logs into a gist](https://gist.github.com/danielballan/5b29ecfa3f1f749ba184fa9041aa7e47#file-gistfile1-txt-L278).

Thanks again for the support. I aim to contribute fixes/documentation back in appreciation for your help.

**Comment by gciotto** [comment]
For deployment, I've been using this [project](https://github.com/lnls-sirius/docker-olog-compose). `docker-compose.yml` defines some variables that forgot to update in `run-docker-olog.sh`. Maybe you might consider using Docker Compose as well! It's pretty simple! :)
Have you run a MySQL container too? I believe I should have mentioned it in README.md.
Thanks a lot!

**Comment by danielballan** [comment]
I see. No, I didn't guess that I would need to run a separate MySQL container. But that is a sensible way to design things. Thanks for the link to the docker-compose work.

**Comment by danielballan** [comment]
So far, so good:

```
$ docker-compose up -d
Starting olog-mysql-db ... done
Starting olog-server ... done
```

Is there an example of something I should curl? Something like...

```
curl --verbose --insecure https://localhost:4848/Olog/resources/logbooks
```

**Comment by gciotto** [comment]
Hi @danielballan,
The port 4848 is used to access a management interface of the Glassfish instance. If you connect to it from your web browser, you should see something like the image below:

![screenshot from 2018-02-12 15-43-34](https://user-images.githubusercontent.com/11737414/36110918-8acb71f6-100b-11e8-8d69-40cde53d2d38.png)

The Olog instance can be acessed from port 8181:

```
$ curl --verbose --insecure https://10.0.6.57:8181/Olog/resources/logbooks

*   Trying 10.0.6.57...
* TCP_NODELAY set
* Connected to 10.0.6.57 (10.0.6.57) port 8181 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=BR; ST=Sao Paulo; L=Campinas; O=LNLS; OU=Controls Group; CN=10.255.0.18
*  start date: Feb  5 10:40:55 2018 GMT
*  expire date: May  6 10:40:55 2018 GMT
*  issuer: C=BR; ST=Sao Paulo; L=Campinas; O=LNLS; OU=Controls Group; CN=10.255.0.18
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /Olog/resources/logbooks HTTP/1.1
> Host: 10.0.6.57:8181
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: GlassFish Server Open Source Edition  4.1.1 
< X-Powered-By: Servlet/3.1 JSP/2.3 (GlassFish Server Open Source Edition  4.1.1  Java/Oracle Corporation/1.8)
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
< Access-Control-Allow-Credentials: true
< Content-Type: application/xml
< Date: Mon, 12 Feb 2018 17:46:34 GMT
< Content-Length: 511
< 
* Connection #0 to host 10.0.6.57 left intact
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><logbooks><logbook owner="gustavo.pinton" name="Controls Group" state="Active"><id>12</id></logbook><logbook name="Electronics Maintenance" state="Active"><id>2</id></logbook><logbook name="LOTO" state="Active"><id>4</id></logbook><logbook name="Mechanical Technicians" state="Active"><id>3</id></logbook><logbook name="Operations" state="Active"><id>1</id></logbook><logbook owner="gustavo.pinton" name="RF" state="Active"><id>22</id></logbook></logbooks>
```

**Comment by danielballan** [comment]
That did it:

```
$ curl -H "Content-Type: application/json" -H "Accept: application/json" -X GET --insecure https://localhost:8181/Olog/resources/logbooks
{"logbook":[{"owner":null,"id":2,"name":"Electronics Maintenance","state":"Active"},{"owner":null,"id":4,"name":"LOTO","state":"Active"},{"owner":null,"id":3,"name":"Mechanical Technicians","state":"Active"},{"owner":null,"id":1,"name":"Operations","state":"Active"}]}
```

Thanks again for your help! Docs PRs forthcoming.

**Comment by danielballan** [comment]
OK, one (last?) question: what the default username and password I should use with the Olog itself? I see `ADMIN_PASSWORD` in the docker files but I'm not sure if this is the password I should use for HTTP authentication.

For example, the request to create a logbook returns `HTTP Status 401 - Unauthorized`:


```
curl -u admin:controle -H "Content-Type: application/json" -H "Accept: application/json" -X POST --insecure https://localhost:8181/Olog/resources/logbooks/test1 -d "{'owner': 'admin', 'name': 'test1'}"
```

I expect I'm just using the wrong username and/or password.

**Comment by gciotto** [comment]
`ADMIN_PASSWORD` is the password you should use in that management interface I sent you in my last comment. It is not related to the Olog authentication itself.
Maybe, this issue is another thing that is badly explained in my README files. In the image, I've set authentication up through a LDAP server (lines 107 to 112 of `setup-olog.sh`).  Unfortunately, I made  only two environment vairables available to customise that connection (`BIND_DN` and `BIND_PASS` in [docker-compose.yml](https://github.com/lnls-sirius/docker-olog-compose/blob/master/docker-compose.yml)). Therefore, you will need to rebuild the image, changing `setup-olog.sh` (lines 28 - 32 and 107 - 112) script with your site's LDAP settings.

**Comment by danielballan** [comment]
I'm trying to run this on a personal laptop, purely for testing purposes, with no LDAP. Is there a default admin user/password I can use for Olog auth?

**Comment by danielballan** [comment]
Hmm. I see that the Olog itself seems to be [deeply tied to LDAP](https://github.com/Olog/olog-service/blob/1fb6a7bc344e6f85aea1a6539185a7fe6d8ebd99/src/site/apt/installation.apt). I don't know enough about the Olog to know if it's possible to just run a test deployment without an LDAP server.

**Comment by gciotto** [comment]
@danielballan, 
Sorry for the late answer, but I weren't at my office in the last days. 
I've never used Olog without an authentication server, so I can't tell if there is way to make this work without such a server.

**Comment by danielballan** [comment]
OK, no worries. I originally thought this might be my shortest path to deploying at test stand for testing an olog client, but I think a VM image from @kshroff is turning out to be a better path for my use case. Thanks again for all the help, @gciotto. I'm going to close this issue.
